### ISSUE TITLE
Result reproducibility

### ISSUE THREAD

**Issue by hvthaibk** [ABurrello/tcn-hard-disk-failure-prediction#2]
Thank you for sharing the code of the excellent work. I am trying to reproduce the results you report in the paper, but it seems that it's not easy to set the right values for many parameters in the Classification.py

Could you please provide those set of values? Many thanks!

**Comment by ABurrello** [comment]
Hello, 
to which parameters are you referring at? They should be specified in the Classification.py file already.

**Comment by hvthaibk** [comment]
Thank you for your quick reply. I am trying to reproduce the results of TCN in Table 2. According to the paper, I think I should set some parameters in Classification.py as follows.
```
model = 'ST3000DM001'
years = ['2014', '2015','2016','2017']
days_considered_as_failure = 7
test_train_perc = 0.3
balancing_normal_failed = 20
history_signal = 90
classifier = 'TCN'
ranking = 'Ok'
num_features = 18
```

There are still some parameters that I cannot find for their references in your papers. Could you please explain their meaning, especially `oversample_undersample, windowing, overlap`
```
perform_features_extraction = False
min_days_HDD = 115
oversample_undersample = 2
windowing = 1
overlap = 1
```

Many thanks in advance

**Comment by ABurrello** [comment]
Hi,
you can leave the as they are. The first parameter refers to the extraction of the futures (not used in TCN). The second is a criterion to exclude HDDs with low days. The third selects the type of oversampling/undersampling. The other two are default values to create the dataset.
