### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by pauln2k** [ABurrello/tcn-hard-disk-failure-prediction#4]
So I am having a few issues with the code regarding reproducing the results and loading the model.

- when running get_dataset you will encounter an error regarding missing directories/files.

- second this I wanted to ask. I am having quite some issues with reproducing the results. 
     - if you set oversample_undersample = 2 this does not apply smote or under sampling for some reason. set it to 1 and fixed some issues with that.
     - I did a few runs for the code with oversample_undersample = 2 (with window 40). the highest results I got were not comparable to the paper values:
     SCORE FDR: 60.076
     SCORE FAR: 0.126
     SCORE F1: 0.684
     SCORE recall: 0.601
     SCORE precision: 0.794

Could you please let me know if there is anything else that should be done to recreate the correct result values? A am currently working on a similar topic and would appreciate if you provide me with some guidance to your code so I could reference and use it.

Thanks!

**Comment by ABurrello** [comment]
Hi,
1. Before running the get_dataset script, you have to create the folder where inserting the dataset;
2. in the oversample_undersample variable: 0 mean undersample, 1 oversample, 2 no balancing techniques applied;
3. Running with oversample_undersample = 2 you are not applying any balancing technique. Therefore, it makes sense you have lower results. Results of Fig.3 when no balancing techniques are applied, are close to the ones you reported. Note also that the results we collected are not with window size = 40.

**Comment by pauln2k** [comment]
Hi,

Just wanted to start by saying thank you so much for the fast reply. So some notes on the code.

I did fix the issue with the Dataset creation. Dataset is created correctly. I did face some issues with the code regarding the Classification.py

Want to double check this:

	# here you can select the model. This is the one tested.
	model = 'ST3000DM001'
	years = ['2014','2015','2016','2017']
	# many parameters that could be changed, both for unbalancing, for networks and for features.
	windowing = 1
	min_days_HDD = 115
	days_considered_as_failure = 7
	test_train_perc = 0.3
	# type of oversampling
	oversample_undersample = 1
	# balancing factor (major/minor = balancing_normal_failed)
	balancing_normal_failed = 20
	history_signal = 32
	# type of classifier
	classifier = 'TCN'
	# if you extract features for RF for example. Not tested
	perform_features_extraction = False
	CUDA_DEV = "1"
	# if automatically select best features
	ranking = 'Ok'
	num_features = 18
	overlap = 1
	
I ran this code and failed some issues with the code going into errors. Just want to double check some things:

- Is this configuration correct for the code (assuming I want window 32)?
- If I run this code (considering I am doing Oversampling SMOTE) using the TCN with window 32, should I not get an FDR of at least above 75% as based on the results shown in figure 4 ( I tried this and got the previous results I showed) ?
- Also is there a specific reason for not using sigmoid since its is a binary classification (0 or 1)?
- is the 'val' column ever used (if yes where exactly)?

small issues I also ran was 
data, target = torch.Tensor(data).cuda(), torch.Tensor(target).cuda() failed so I changed it to 
data, target = torch.Tensor(data).cuda(), torch.Tensor(target.values).cuda()

Thank you for the support. Really appreciate it. Will surely cite this paper when aiming to publish.

Thanks!

**Comment by pauln2k** [comment]
Also I have noticed that you are dropping 'invalid' windows form the dataset could you very briefly explain the reasoning behind this? I'm a bit confused why these windows are considered invalid.

**Comment by ABurrello** [comment]
Yes, you should get these results. Please check your dataset with Table 1 of the dataset, to check if the dataset is correctly created. I think the issue could be there
